create database AYP_DB;
create role AYP_role_1;

use database AYP_DB;
create schema AYP_schema;

use schema AYP_schema;
CREATE OR ALTER TABLE AYP_table_1 (
  a INT PRIMARY KEY,
  b VARCHAR(20)
)
DEFAULT_DDL_COLLATION = 'fr';

create view AYP_view_1 (
 a INT PRIMARY KEY,
  b VARCHAR(20)
);
CREATE VIEW AYP_view_1 COMMENT='Test view' AS SELECT * FROM AYP_table_1;

GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE AYP_DB TO ROLE AYP_role_1;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE AYP_DB TO ROLE AYP_role_1;
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE AYP_DB TO ROLE AYP_role_1;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE AYP_DB TO ROLE AYP_role_1;
GRANT usage ON ALL SCHEMAS IN DATABASE AYP_DB TO ROLE AYP_role_1;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE AYP_DB TO ROLE AYP_role_1;


grant select on all tables in schema MY_DB.MY_SCHEMA to role TEST_ROLE;
GRANT ALL PRIVILEDGES ON FUTURE VIEWS ON database DB_CONSUMPTION TO ROL O365_GRP_GFSSCORP_SFL_DL_PRO_ITDATA_OPER;
GRANT ALL PRIVILEDGES ON TABLES ON database DB_CONSUMPTION TO ROL O365_GRP_GFSSCORP_SFL_DL_PRO_ITDATA_OPER;
GRANT ALL PRIVILEDGES ON FUTURE TABLES ON database DB_CONSUMPTION TO ROL O365_GRP_GFSSCORP_SFL_DL_PRO_ITDATA_OPER;


USE DATABASE SNOWFLAKE;
USE SCHEMA ACCOUNT_USAGE;
SELECT * FROM SNOWFLAKE.ACCOUNT_USAGE.GRANTS_TO_ROLES;

-- GRANTS SOLICITADOS A PROTECT
TABLAS | VISTAS | ESQUEMAS
GRANT ALL PRIVILEGES ON ALL TABLES IN DATABASE {BASES_DE_DATOS_DE_CONSUMO} TO ROLE O365_GRP_GFSSCORP_SFL_DL_PRO_ITDATA_OPER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE {BASES_DE_DATOS_DE_CONSUMO} TO ROLE O365_GRP_GFSSCORP_SFL_DL_PRO_ITDATA_OPER;
GRANT ALL PRIVILEGES ON ALL VIEWS IN DATABASE {BASES_DE_DATOS_DE_CONSUMO} TO ROLE O365_GRP_GFSSCORP_SFL_DL_PRO_ITDATA_OPER;
GRANT ALL PRIVILEGES ON FUTURE TABLES IN DATABASE {BASES_DE_DATOS_DE_CONSUMO} TO ROLE O365_GRP_GFSSCORP_SFL_DL_PRO_ITDATA_OPER;
GRANT usage ON ALL SCHEMAS IN DATABASE {BASES_DE_DATOS_DE_CONSUMO} TO ROLE O365_GRP_GFSSCORP_SFL_DL_PRO_ITDATA_OPER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE {BASES_DE_DATOS_DE_CONSUMO} TO ROLE O365_GRP_GFSSCORP_SFL_DL_PRO_ITDATA_OPER;


